version: '3'
services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - sonarnetwork
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - sonarnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sonar
      - MYSQL_PASSWORD=sonar
      - MYSQL_DATABASE=sonar
  app:
    image: devopsProject
    ports:
      - "8082:8080"  # Adjust the port as needed
    networks:
      - sonarnetwork

networks:
  sonarnetwork:
    driver: bridge
