version: "3"
services:

  mysqldb:
    image: mysql
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db_vol:/var/lib/mysql
      -
  backend_app:
    image: syndamejri/project-devops:latest
    container_name: backend_app
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port":"8082",
        "spring.datasource.url":"jdbc:mysql://localhost:3306/devops_project?createDatabaseIfNotExist=true",
        "spring.datasource.username":"root",
        "spring.datasource.password":"",
        "spring.jpa.show-sql":"true"
        "spring.jpa.hibernate.ddl-auto":"update"
          }'
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    restart: on-failure
    stdin_open: true
    tty: true
